### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by michalpiekarski** [bindydijurido/asta#2]
Currently there is a [readme.txt](https://github.com/bindydijurido/asta/blob/master/readme.txt) file provided.
This is great to have but I would suggest to use the common pattern of **README.md**.
Markdown provides powerful and simple formatting options and can be easily converted to many different formats.
Additionally many platforms, tools and services are looking for exactly this file which can become very handy.

**Comment by bindydijurido** [comment]
thanks. fixed.
