### ISSUE TITLE
Second readme file in HelloWorld folder

### ISSUE THREAD

**Issue by michalpiekarski** [bindydijurido/asta#3]
It's not very clear for me, why there is a second [readme.txt](https://github.com/bindydijurido/asta/blob/master/Hello%20World/readme.txt) file inside the **Hello World** folder.
If the contents of this file are included in the top level readme file it could improve the visibility and prevent information fragmentation in the repository.

**Comment by bindydijurido** [comment]
it's fixed right now. thanks for your feedback <3
