### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by michalpiekarski** [bindydijurido/asta#4]
I would find it very useful if there were at least links to the dependencies mentioned in [readme.txt](https://github.com/bindydijurido/asta/blob/master/Hello%20World/readme.txt).
Configuration file for some tool like _Gulp_ or _Grunt_ could be much better, but a simple link where I can download the necessary requirements would help a lot.

**Comment by bindydijurido** [comment]
it is fixed and improved. thanks for your feedback <3
