### ISSUE TITLE
Magic path

### ISSUE THREAD

**Issue by michalpiekarski** [bindydijurido/asta#6]
There is a possible problem with setting [`webdriver.geco.driver`](https://github.com/bindydijurido/asta/blob/master/Hello%20World/asta/Task_1.java#L38) system property.
What if I have **Eclipse** installed in a different folder?
Is it possible to make this value more dynamic of easily configurable?

**Comment by bindydijurido** [comment]
it's fixed right now. thanks for your feedback and your help.
