### ISSUE TITLE
Inconsistent structure

### ISSUE THREAD

**Issue by michalpiekarski** [bindydijurido/asta#8]
Classes `Task1` and `Task2` use somewhat inconsistent coding structure.
It could be much more readable is there was one structure used consistently.
```
return (By) By.xpath(Root.getRoot() +
```

The inconsistent pattern looks like:
```
return (By) By.xpath(String.format(Root.getRoot() +
```

**Comment by bindydijurido** [comment]
fixed. thanks for feedback <3
